name: flutube
description: Flutter plugin that facilitates the embed of YT videos without using the official YT API. Fork from https://github.com/ja2375/FluTube
version: 0.8.1
author: Emanuel Braz <fastencoding@gmail.com>
homepage: https://github.com/MagmaShared/youtube_player.git

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ">= 0.12.0 <0.13.0"
  chewie: ">=0.9.7 <0.10.0"
  flutter:
    sdk: flutter

flutter:
